language: java
jdk: openjdk8
install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
cache:
  directories:
  - $HOME/.m2
deploy:
- provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_API_KEY
  file_glob: true
  draft: true
  file:
  - "app/target/classes/asm_files/update.sh"
  - "app/target/touchHome.jar.md5"
  - "app/target/touchHome.jar"
  on:
    tags: true

- provider: bintray
  skip_cleanup: true
  user: $BINTRAY_USER
  key:  $BINTRAY_KEY
  file: 'bintray.json'
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: bash docker-push.sh $USER
  on:
    tags: true

