package org.homio.addon.imou.internal.cloud.dto;

import java.util.List;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
// https://open.imoulife.com/book/en/http/device/live/bindDeviceLive.html
public class ImouDeviceLiveBindDTO {

    private List<Stream> streams;
    // Type of live source (1: device; 2: stream address)
    private int liveType;
    // Video cover update frequency (unit: s)
    private int coverUpdate;
    // Live broadcast authorization token
    private String liveToken;
    // Device serial number
    private String deviceId;
    // Live broadcast status (1: open; 2: pause; 3: insufficient traffic)
    private int liveStatus;
    // Channel number
    private String channelId;
    private List<Job> job;

    @Getter
    @Setter
    @ToString
    public static class Job {

        // Duty cycle
        private String period;
        // Live broadcast plan status (true: on; false: off)
        private boolean status;
    }

    @Getter
    @Setter
    @ToString
    public static class Stream {

        // Live stream hls access address
        private String coverUrl;
        // Live stream hls access address
        private String hls;
        // Stream type (0: HD main stream; 1: SD secondary stream) (when the live broadcast address is generated by the rtsp source, this field is not
        // available)
        private int streamId;
    }
}
