spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  banner:
    location: classpath:/banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10
          lob:
            non_contextual_creation: true
    show-sql: false

server:
  port: 9111
