rootDir: /opt/touchhome
artifactoryFilesURL: https://touchhome.jfrog.io/artifactory/files-remote

touchhome:
  version: @project.version@
  internet-test-interval: PT10S
  max-java-script-compile-before-interrupt: PT5S
  max-java-script-once-call-before-interrupt: PT60S
  server-site-url: https://touchhome.org
  http-port: 9119
  check-port-interval: PT10S
  disable-security: false
  min-script-thread-sleep: PT0.1S

spring:
  banner:
    location: classpath:/banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10
          lob:
            non_contextual_creation: true
    show-sql: false

server:
  port: 9111
