spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  banner:
    location: classpath:/banner.txt
  sql.init.mode: never
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9111
