spring:
  data.jpa.repositories.bootstrap-mode: lazy
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  banner:
    location: classpath:/banner.txt
  sql.init.mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 9111
  tomcat:
    connection-timeout: PT30M
    max-connections: 100
    max-http-form-post-size: 2MB
    threads:
      max: 100
      max-queue-capacity: 1000
  compression:
    enabled: true
    min-response-size: 512B

ssl:
  client-auth: true
  keystore-path: identity.jks
  keystore-password: secret
  truststore-path: truststore.jks
  truststore-password: secret